### ISSUE TITLE
Plugin::ExtraTests does not move test's prereqs between phases

### ISSUE THREAD

**Issue by liosha** [rjbs/Dist-Zilla#483]
ExtraTests rewrites tests from xt/ to t/,
so it should move test's prereqs from 'develop' phase to 'build',
but it doesn't.

**Comment by karenetheridge** [comment]
I see a few errors in your analysis:

 * prereqs for things in t/ should be in 'test', not 'build' (see https://metacpan.org/pod/CPAN::Meta::Spec#Phases)
 * once a prereq has been added, its origin is unknown, so there is no way to identify which prereqs belong to particular test files
 * [ExtraTests] adds a guard at the top, prohibiting their running unless a particular environment variable is set, because it's never the intent to allow these tests to run for normal user installation. Therefore additional prerequisites should not be added to where a normal user installation would pick them up.

**Comment by rjbs** [comment]
I agree with @karenetheridge, especially the third point.
