### ISSUE TITLE
Dist::Zilla::Tester deletes tmp too zealously

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Dist-Zilla#503]
capturing before the nopaste vanishes:

10:59 <%ether> iirc there is a PR deep down in the queue for this
11:00 <%ether> i.e. "don't be so zealous about blowing away tmp/ -- other processes may still be using it"

```
#   Failed test 'ASCII-only author'
#   at t/plugins/license.t line 34.
# Exception in subtest 'ASCII-only author': Error in tempdir() using tmp/XXXXXXXXXX: Parent directory (tmp) does not exist at /Users/ether/.cpanm/work/1446054814.49644/Dist-Zilla-5.041/blib/lib/Dist/Zilla/Tester.pm line 135.
Error in tempdir() using tmp/XXXXXXXXXX: Parent directory (tmp) does not exist at /Users/ether/.cpanm/work/1446054814.49644/Dist-Zilla-5.041/blib/lib/Dist/Zilla/Tester.pm line 135.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/plugins/license.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests
```

**Comment by rjbs** [comment]
The queue isn't that long, and I don't see anything like this.  Let me know if you find one.

**Comment by karenetheridge** [comment]
This still happens occasionally for me, but I have been unable to find the problem each time I look (although each time I'm usually in a hurry and don't have time for anything but a quick driveby). I'm inclined to think this will be fixed by cleaning up the use of Path::Class in Dist::Zilla::Tester.  Only randomly-generated tmpdirs should be blown away on scope exit, not tmp itself!

**Comment by kentfredric** [comment]
Its unfortunately incredibly hard to reproduce, because the exact conditions needed to create it are:

- All jobs that are running bar one are in cleanup phase
- Thus, all tmp/* directories are gone
- Thus, the "last one out" gets `rmdir` to succeed.

And this needs to happen at *exactly* the right time between the mkdir  and the subsequent File::Temp->newdir() calls: 

https://metacpan.org/source/RJBS/Dist-Zilla-5.047/lib/Dist/Zilla/Tester.pm#L284-289

The problem I think is not so much the over-zealous culling of temp dirs, but that the "create a tempdir" is not properly guarded against race conditions nuking the tempdir.

To further exacerbate the situation, you can simulate the "all threads done and rmdir getting called" with the following perl script running in the background :

```perl

#!perl
use strict;
use warnings;

while(1) {
  if ( rmdir 'tmp' ) {
    warn "removed /tmp successfully\n";
  }
}
```

This pushes the lack of race condition error handling into view quite substantially, and causes even a single-threaded prove to fail.

Simply increasing the time between rmdir calls in this code can be the difference between everything failing and nothing failing.

Here's however a single threaded test pass with a 0.002 second delay inserted at the top of that while loop.

```
 prove -j1 -lr t/
t/01-basic.t .................... ok   
t/02-not-installed.t ............ ok   
t/03-bunk-module.t .............. ok   
t/04-two-configs.t .............. ok   
t/05-check-all-prereqs.t ........ removed /tmp successfully
Error in tempdir() using tmp/XXXXXXXXXX: Parent directory (tmp) does not exist at /home/kent/perl5/perlbrew/perls/5.25.1-nossp-sdbm-nopmc/lib/site_perl/5.25.1/Dist/Zilla/Tester.pm line 142.
t/05-check-all-prereqs.t ........ Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/06-duplicates.t ............... removed /tmp successfully
Error in tempdir() using tmp/XXXXXXXXXX: Could not create directory tmp/kkpe4yZuqX: No such file or directory at /home/kent/perl5/perlbrew/perls/5.25.1-nossp-sdbm-nopmc/lib/site_perl/5.25.1/Dist/Zilla/Tester.pm line 142.
t/06-duplicates.t ............... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/07-two-stale.t ................ ok   
t/08-many-modules.t ............. ok   
t/10-release-prompt.t ........... ok   
t/11-local-module.t ............. ok   
t/12-skip.t ..................... ok   
t/13-fatal.t .................... ok   
t/14-index-base-url.t ........... ok   
t/15-command.t .................. ok   
t/16-command-all.t .............. ok   
t/17-command-missing-plugins.t .. ok   
t/18-command-old-plugins.t ...... ok   
t/19-build-failure.t ............ ok   
t/20-ensure-not-stale.t ......... ok   
t/21-authordeps.t ............... ok   
t/22-perl.t ..................... removed /tmp successfully
Error in tempdir() using tmp/XXXXXXXXXX: Parent directory (tmp) does not exist at /home/kent/perl5/perlbrew/perls/5.25.1-nossp-sdbm-nopmc/lib/site_perl/5.25.1/Dist/Zilla/Tester.pm line 142.
t/22-perl.t ..................... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/23-noninteractive.t ........... removed /tmp successfully
Error in tempdir() using tmp/XXXXXXXXXX: Could not create directory tmp/SMIKMPGunw: No such file or directory at /home/kent/perl5/perlbrew/perls/5.25.1-nossp-sdbm-nopmc/lib/site_perl/5.25.1/Dist/Zilla/Tester.pm line 142.
t/23-noninteractive.t ........... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/24-unindexed-core-modules.t ... ok   
t/25-core-modules.t ............. ok   
t/26-command-missing-module.t ... ok    
t/27-travis.t ................... removed /tmp successfully
Error in tempdir() using tmp/XXXXXXXXXX: Parent directory (tmp) does not exist at /home/kent/perl5/perlbrew/perls/5.25.1-nossp-sdbm-nopmc/lib/site_perl/5.25.1/Dist/Zilla/Tester.pm line 142.
    # Child (run_under_travis = 1) exited without calling finalize()
t/27-travis.t ................... 1/? 
#   Failed test 'run_under_travis = 1'
#   at /home/kent/perl5/perlbrew/perls/5.25.1-nossp-sdbm-nopmc/lib/site_perl/5.25.1/Test/Builder.pm line 279.
# status of filehandles: {
#   '-c STDOUT' => '',
#   '-f STDOUT' => '',
#   '-t STDIN' => 1,
#   '-t STDOUT' => ''
# }
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 1.
t/27-travis.t ................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/1 subtests 
t/zzz-check-breaks.t ............ ok   

Test Summary Report
-------------------
t/05-check-all-prereqs.t      (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/06-duplicates.t             (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/22-perl.t                   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/23-noninteractive.t         (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/27-travis.t                 (Wstat: 512 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=27, Tests=96, 22 wallclock secs ( 0.09 usr  0.05 sys + 20.39 cusr  1.59 csys = 22.12 CPU)
Result: FAIL
```

Given a sensitivity of a 0.002 second window is enough to make-or-break this, that speaks to me in terms of "gosh, you have to be lucky to get that happening when all the dzil things take so much cpu time".

**Comment by kentfredric** [comment]
> Only randomly-generated tmpdirs should be blown away on scope exit, not tmp itself!

That's actually kinda what's happening, modulo interpretation. 

Dzil is not recursively purging `tmp/`, instead, its relying entirely on File::Temp to kill `tmp/<random>` during DEMOLISH.

Dzil only then opportunistically calls `rmdir tmp` ( and then ignores the return code ) so that the dir `tmp` is only reaped when it is empty, and left in place when it is not. https://metacpan.org/source/RJBS/Dist-Zilla-5.047/lib/Dist/Zilla/Tester.pm#L65-68

Which is what makes this so hard to reproduce, because if you even have as much as *one* instance of a File::Temp::Dir object in any fork, then the problem won't happen.

**Comment by kentfredric** [comment]
Though the general nature of the problem can be demonstrated without any Dzil specific code reasonably quickly, because being very lightweight makes the problems happen fast enough to widen the race condition windows.

```perl

#!perl
use strict;
use warnings;

use File::Temp;
my @waits;

# Note: its important you start off in a dir without a tmp/
# because if tmp/ exists and has as much as one file in it, the problem won't happen
# because all the rmdir calls will silently fail, and so File::Temp->newdir() calls
# will all succeed due to an existing "tmp"
my $workdir = File::Temp->newdir( 
  TMPDIR => 1,
);

# Emulates a test harness running lots of jobs
for my $job ( 0 .. 1000 ) {
  my $pid = fork();
  if ( $pid ) {
    push @waits, $pid;
    next;
  }
  chdir "$workdir";
  # DZil logic starts here
  mkdir 'tmp'; 
  {
    my $tempdir = File::Temp->newdir( CLEANUP => 1, DIR => 'tmp' );
  }
  rmdir 'tmp';
  exit;
}

for my $job ( @waits ) {
  waitpid $job, 0;
}
```

**Comment by dolmen** [comment]
So the fix seems to not rely on a [static `tmp` directory](https://metacpan.org/source/RJBS/Dist-Zilla-5.047/lib/Dist/Zilla/Tester.pm#L136) as a default but instead a randomized one, isn't it?

**Comment by kentfredric** [comment]
That's *a* fix. The other fix would be to do what TempDir::Tiny does, and spin-loop generating the path in a way that competing processes don't trim, and then only proceeding on success, with a milisecond sleep between loops, and upon failing multiple times, fallback to using a global fully random tempdir instead of a local one.

That way, the workflow is:
```
   0:
   mkdir tmp/
   mkdir tmp/<RANDOM>  
   failed? -> 
        n_fails < threshold ?
           select( undef,undef, undef, <SMALLVALUE>
           goto 0
        <globaltempdir>
    <SUCCESS>
```

https://metacpan.org/source/DAGOLDEN/Test-TempDir-Tiny-0.016/lib/Test/TempDir/Tiny.pm#L142-183

**Comment by karenetheridge** [comment]
It would be nice if we could just use Test::TempDir::Tiny to do the heavy lifting, but instead of getting a randomly-named directory, it was always called tmp.
