### ISSUE TITLE
dzil authordeps --missing doesn't show up bundle version requierement in filter

### ISSUE THREAD

**Issue by celogeek** [rjbs/Dist-Zilla#511]
When we specify a specific bundle version with filter this way :

```
[@Filter]
-bundle                 = @MyBundle
-version                = 0.08
```

and when my bundle is in v0.07, I've got this with dzil build :

```
Required plugin Dist::Zilla::PluginBundle::MyBundle isn't installed.

Run 'dzil authordeps' to see a list of all required plugins.
You can pipe the list to your CPAN client to install or update them:

    dzil authordeps --missing | cpanm
```

But when I run 

```
dzil authordeps --missing
```

nothing show up.

dzil authordeps should return the bundle if the version doesn't match in the filter rule.

**Comment by karenetheridge** [comment]
Unfortunately, that's not how `authordeps` works -- it is very stupid, not running any plugin code, and simply looks for names of plugins and bundles in `[]` that are missing.

`dzil listdeps --develop --missing` won't get you there either, except via the same error you've already seen.

(However, `dzil stale --all` will, which uses Dist::Zilla::App::Command::stale that I wrote to make this problemspace a little nicer, because it carefully executes the plugins in a `try{}` block and catches the missing plugin exceptions for you to turn it into a nicer error message.)

**Comment by celogeek** [comment]
So they is not real way to have bundle dependencies version in our dist.ini ?
May be authordeps can do a stupid detection with supporting the "Filter => version".

If filter is seen, it check the Bundle, then if the version is present it just check if the bundle has the right version ?

or may be we can just change dzil authordeps --missing | cpanm by dzil authordeps | cpanm

**Comment by dolmen** [comment]
To workaround manually the fact that the `[@Filter]` mecanism is hidding your dependency from standard detection tools, just put this line in `dist.ini` so that the bundle is reported by `dzil authordeps`:
```
; authordep Dist::Zilla::PluginBundle::MyBundle
```
And put this line so that the bundle and its version are checked and reported by `dzil listdeps --develop`:
```
[Prereqs / DevelopRequires]
Dist::Zilla::PluginBundle::MyBundle=0.08
```

However a better fix is to not use `[@Filter]` at all because that's what is blocking detection. But that requires that the bundle provides the filtering support itself. You can do that by adding to the bundle the role [PluginRemover](https://metacpan.org/pod/Dist::Zilla::Role::PluginBundle::PluginRemover). You'll also probably want to use the [Config::Slicer](https://metacpan.org/pod/Dist::Zilla::Role::PluginBundle::Config::Slicer) role.

**Comment by dolmen** [comment]
@celogeek Did the answer fit your need?

**Comment by celogeek** [comment]
Yeah it work. I close this.
