### ISSUE TITLE
Drop Log::Dispatchouli dependency

### ISSUE THREAD

**Issue by dolmen** [rjbs/Dist-Zilla#541]
dzil only logs to the console with 3 levels: `log`, `log_debug`, `log_fatal`.
This is currently implemented with Log::Dispatchouli (which uses Log::Dispatch).
This brings much latency to dzil runtime for what is just print statements at the end.
I propose to replace the logger with something lighter.

I haven't checked if/how Log::Dispatchouli features are used for Test::Dzil.

**Comment by rjbs** [comment]
I don't want to say "absolutely not."  Or, rather, I do want to say that, but I'm trying to be open-minded.  Still, there are places where I just want to say, "this part will not get much faster, because I want to continue using the tools I like to use without worry."  So, keep in mind that I am already sort of 😐 on this.
