### ISSUE TITLE
"dzil listdeps" fails on a fresh system (missing module)

### ISSUE THREAD

**Issue by akarelas** [rjbs/Dist-Zilla#560]
I have Ubuntu 14.04, I used to use dzil to release my module (XML::MyXML) for years. Now I deleted ~/perl5 and started with a fresh perl5 dir to install new version of Dist::Zilla. I cpanm -L ~/perl5 Dist::Zilla, then I dzil authordeps --missing | cpanm -L ~/perl5, that went well, but when I did this, I got an error:

```
karjala@modules-vm:~/modules/XML-MyXML$ dzil listdeps
Can't locate Pod/Elemental/Transformer/List.pm in @INC (you may need to install the Pod::Elemental::Transformer::List module) (@INC contains: /home/karjala/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/karjala/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/karjala/perl5/lib/perl5/Module/Runtime.pm line 317.
karjala@modules-vm:~/modules/XML-MyXML$ 
```

**Comment by karenetheridge** [comment]
I took a look at your distribution at https://metacpan.org/release/XML-MyXML
-- since you chose to exclude dist.ini and weaver.ini from upload (please
don't do that - it prevents dzil authors from using grep.cpan.me to find users
of their plugins and notify you of changes), I found your repository at
https://github.com/akarelas/xml-myxml.  Your weaver.ini references the list
transformer, which is Pod::Elemental::Transformer::List -- you need to add
this as an `; authordep` to dist.ini manually for `dzil authordeps --missing`
to pick it up.

It might be possible for the PodWeaver plugin to automatically inject
'develop' prereqs for all the weaver.ini plugins (patches welcome), but that
still won't change anything for the authordeps command, as it doesn't execute
plugins.

**Comment by akarelas** [comment]
I see. I uploaded new version of my module with dist.ini & weaver.ini, and added `; authordep <something>`

I'm closing this issue now.

**Comment by hakonhagland** [comment]
> you need to add this as an `; authordep` to `dist.ini` manually for `dzil authordeps --missing` to pick it up.

@karenetheridge Where is this `; authordep` documented? I ran into the same issue here https://github.com/jkg/Telegram-Bot/blob/master/weaver.ini

**Comment by Grinnz** [comment]
It is primarily documented here: https://dzil.org/tutorial/prereq.html as well as in the authordeps command https://metacpan.org/pod/Dist::Zilla::App::Command::authordeps
